image:
  tag: "1.0.0-snapshot-fa3167db41bf"
  pullPolicy: IfNotPresent
liquibase:
  image:
    tag: "liquibase-1.0.0-snapshot-fa3167db41bf"
    pullPolicy: IfNotPresent
deploymentRevision: fa3167db41bfafc8ef02aa596ad9774c96a356b2-33657151625-1
