image:
  tag: "1.0.0-snapshot-deafe5cd9fcf"
  pullPolicy: IfNotPresent
liquibase:
  image:
    tag: "liquibase-1.0.0-snapshot-deafe5cd9fcf"
    pullPolicy: IfNotPresent
deploymentRevision: deafe5cd9fcf29a7358f3d2de347d46d53c9ad0e-33412482407-1
